name: Java CI

on: [push]

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install pytest allure-pytest
    - name: Run test
      run: pytest --alluredir=./allure_results .
